<a href="https://colab.research.google.com/github/Fathimafdz/Internship/blob/main/Day2_Numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**numpy**

In [ ]:
#sum of list
list1=[1,2,3,4]
list2=[5,6,7,8]


In [ ]:
sum1=list1+list2

In [ ]:
sum1

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sum_1=[]
for num1,num2, in zip(list1,list2):
     sum_1.append(num1+num2)
sum_1  

[6, 8, 10, 12]

In [ ]:
import numpy as np
arr1=np.array(list1)
arr1

array([1, 2, 3, 4])

In [ ]:
arr2 =np.array(list2)
arr2

array([5, 6, 7, 8])

In [ ]:
sum_l1=arr1+arr2

In [ ]:
sum_l1


array([ 6,  8, 10, 12])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
list3=[[2,3,4],[5,6,7]]

In [ ]:
arr3=np.array(list3)

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 3)

In [ ]:
arr4=np.arange(8)

In [ ]:
arr4

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr5=arr4.reshape(2,4)

In [ ]:
arr5

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr4.mean()

3.0

In [ ]:
arr4.sum()

28

In [ ]:
np.median(arr4)

3.5

In [ ]:
arr5

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

**Pandas**

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/auto-mpg.csv')